package com.pea2u.letter2Future.model;

public class Letter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column letter.id
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column letter.title
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column letter.img
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column letter.video
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    private String video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column letter.content
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    private byte[] content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column letter.id
     *
     * @return the value of letter.id
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column letter.id
     *
     * @param id the value for letter.id
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column letter.title
     *
     * @return the value of letter.title
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column letter.title
     *
     * @param title the value for letter.title
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column letter.img
     *
     * @return the value of letter.img
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column letter.img
     *
     * @param img the value for letter.img
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column letter.video
     *
     * @return the value of letter.video
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column letter.video
     *
     * @param video the value for letter.video
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column letter.content
     *
     * @return the value of letter.content
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column letter.content
     *
     * @param content the value for letter.content
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    public void setContent(byte[] content) {
        this.content = content;
    }
}