server:
  port: 8100

spring:
  profiles:
    active: local
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  config-location:
    - classpath:mybatis/mybatis-config.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 7200 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

wx:
  authUrl: https://api.weixin.qq.com/sns/jscode2session
  secret: 5c8600af1dd565eaa8cf222e93746f58
  grantType: authorization_code


letter2future:
  sysParamPermitString: index_notice,index_notice2

