server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  config-location:
    - classpath:mybatis/mybatis-config.xml
