spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/letter2future?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: letter2future
    password: whoIsNo.1
    driver-class-name: com.mysql.cj.jdbc.Driver


