package com.pea2u.letter2Future.mapper;

import com.pea2u.letter2Future.model.Letter;

public interface LetterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letter
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letter
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    int insert(Letter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letter
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    int insertSelective(Letter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letter
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    Letter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letter
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    int updateByPrimaryKeySelective(Letter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letter
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Letter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letter
     *
     * @mbg.generated Tue Jun 04 16:48:15 CST 2019
     */
    int updateByPrimaryKey(Letter record);
}